mine:
  origin:
    x: 100
    y: 100
    z: 100
  size:
    x: 16
    y: 16
    z: 16
  # [FIXED]
  # block: 'material[:data]'
  #
  # [RANDOM]
  # blocks:
  # - '10:material[:data]'
  # - '90:material[:data]'
  #
  # [SCHEMATIC]
  # file: <data/folder/path>
  fill-strategy:
    type: 'FIXED'
    block: 'GOLD_BLOCK'